[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
serde = { version = "1.0.216", default-features = false }
uuid = { version = "1.11.0", default-features = false }

